# https://docs.railway.com/reference/config-as-code
[build]
builder = "nixpacks"

[deploy]
startCommand = ".venv/bin/python manage.py migrate --noinput && .venv/bin/gunicorn bootstrap.wsgi:application --config gunicorn.conf.py"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
healthcheckPath = "/products/"
healthcheckTimeout = 120
