from django.urls import path

from . import admin_views, auth_views, client_booking_views, contact_views, map_views, report_views, salon_owner_views, slot_views, views, worker_views

urlpatterns = [
    path('', views.index),
    path('contact/', contact_views.create_contact_message, name='create_contact_message'),
    path('contact/info/', contact_views.get_contact_info, name='get_contact_info'),
    path('salons/', contact_views.list_public_salons, name='list_public_salons'),
    path('salons/<slug:slug>/', contact_views.get_public_salon_detail, name='get_public_salon'),
    path('bookings/', views.create_booking, name='create_booking'),
    path('bookings/mine/', views.my_bookings, name='my_bookings'),
    path('bookings/mine/<int:booking_id>/cancel/', client_booking_views.cancel_my_booking, name='cancel_my_booking'),
    path('bookings/mine/<int:booking_id>/reschedule/', client_booking_views.reschedule_my_booking, name='reschedule_my_booking'),
    path('bookings/list/', views.list_bookings, name='list_bookings'),
    path('bookings/worker/', worker_views.worker_bookings, name='worker_bookings'),
    path('owner/me/', salon_owner_views.owner_me, name='owner_me'),
    path('owner/salons/', salon_owner_views.list_owner_salons, name='owner_list_salons'),
    path('owner/salons/create/', salon_owner_views.create_owner_salon, name='owner_create_salon'),
    path('owner/salons/<int:salon_id>/', salon_owner_views.update_owner_salon, name='owner_update_salon'),
    path('owner/salons/<int:salon_id>/staff/', salon_owner_views.list_owner_salon_staff, name='owner_salon_staff'),
    path('owner/technicians/', salon_owner_views.list_assignable_technicians, name='owner_assignable_technicians'),
    path('owner/technicians/<int:user_id>/salon/', salon_owner_views.assign_technician_salon, name='owner_assign_technician'),
    path('workers/', worker_views.list_public_workers, name='list_public_workers'),
    path('workers/<int:worker_id>/schedule/', worker_views.public_worker_schedule, name='public_worker_schedule'),
    path('map/nearby/', map_views.nearby_map_markers, name='nearby_map_markers'),
    path('bookings/<int:booking_id>/accept/', worker_views.accept_booking, name='accept_booking'),
    path('bookings/<int:booking_id>/cancel/', worker_views.cancel_booking_worker, name='cancel_booking_worker'),
    path('slots/', slot_views.list_available_slots, name='list_available_slots'),
    path('slots/manage/', slot_views.manage_slots, name='manage_slots'),
    path('slots/toggle/', slot_views.toggle_slot, name='toggle_slot'),
    path('slots/off-day/', worker_views.off_day, name='off_day'),
    path('auth/register/', auth_views.register, name='register'),
    path('auth/signup-config/', auth_views.signup_config, name='signup_config'),
    path('auth/csrf/', auth_views.csrf_bootstrap, name='csrf_bootstrap'),
    path('auth/login/', auth_views.login_view, name='login'),
    path('auth/forgot-password/', auth_views.forgot_password, name='forgot_password'),
    path('auth/reset-password/', auth_views.reset_password, name='reset_password'),
    path('auth/logout/', auth_views.logout_view, name='logout'),
    path('auth/me/', auth_views.me, name='me'),
    path('auth/me/update/', auth_views.update_profile, name='update_profile'),
    path('admin/salons/', admin_views.list_salons, name='admin_list_salons'),
    path('admin/salons/create/', admin_views.create_salon, name='admin_create_salon'),
    path('admin/salons/<int:salon_id>/', admin_views.update_salon, name='admin_update_salon'),
    path('admin/stats/', admin_views.stats, name='admin_stats'),
    path('admin/messages/', admin_views.list_contact_messages, name='admin_list_messages'),
    path('admin/contact-info/', admin_views.get_salon_contact_info, name='admin_get_contact_info'),
    path('admin/contact-info/update/', admin_views.update_salon_contact_info, name='admin_update_contact_info'),
    path('admin/users/', admin_views.list_users, name='admin_list_users'),
    path('admin/users/<int:user_id>/role/', admin_views.update_user_role, name='admin_update_role'),
    path('admin/users/<int:user_id>/salon/', admin_views.update_user_salon, name='admin_update_user_salon'),
    path('admin/users/<int:user_id>/showcase/', admin_views.update_technician_showcase, name='admin_update_technician_showcase'),
    path('admin/bookings/create/', admin_views.create_walk_in_booking, name='admin_create_walk_in_booking'),
    path('admin/technicians/pending/', admin_views.list_pending_technicians, name='admin_pending_technicians'),
    path('admin/technicians/<int:user_id>/approve/', admin_views.approve_technician, name='admin_approve_technician'),
    path('admin/technicians/<int:user_id>/reject/', admin_views.reject_technician_view, name='admin_reject_technician'),
    path('admin/bookings/<int:booking_id>/', admin_views.delete_booking, name='admin_delete_booking'),
    path('reports/summary/', report_views.report_summary, name='report_summary'),
    path('reports/by-service/', report_views.report_by_service, name='report_by_service'),
    path('reports/by-venue/', report_views.report_by_venue, name='report_by_venue'),
    path('reports/by-worker/', report_views.report_by_worker, name='report_by_worker'),
    path('reports/timeline/', report_views.report_timeline, name='report_timeline'),
    path('reports/export/', report_views.export_bookings_csv, name='report_export'),
]
   